config/routes.rb
Rails.application.routes.draw do
  # namespace :settings do
  #   get 'users/show'
  #   get 'users/update'
  # end
  # get 'posts/create'
  # get 'timelines/index'
  # get 'timelines/show'
  devise_for :users
  root to: 'home#index'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  namespace :settings do
    resource :user, only: %i[show update]
  end
  authenticate :user do
    resources :timelines,
              only: %i[index show],
              param: :username
    resources :posts, only: %i[create show]
    resources :bonds, param: :username do
      member do
        post :follow
        post :unfollow
        post :accept
        post :reject
        get :followers
        get :following
      end
    end
  end
  namespace :api do
    namespace :v1 do
      resources :places, only: [:index]
    end
  end
end

app/views/layouts/member/_navbar.html.erb
<nav class="topnav">
  <div class="flex items-center flex-shrink-0">
    <%= link_to timelines_path do %>
      <h1>tandibi</h1>
    <% end %>
    <%= link_to settings_user_path,
      class: "linked-icon #{"active" if on_settings?}" do %>
      <%= evil_icon "ei-gear" %>
    <% end %>
  </div>
  <div class="block flex-grow flex items-center w-auto">
    <div class="text-sm flex-grow">
      <%= link_to timelines_path,
        class: "linked-icon #{"active" if on_bunch?}" do %>
        <%= evil_icon "ei-timeline" %>
      <% end %>
      <%= link_to timeline_path(current_user),
        class: "linked-icon #{"active" if on_self?}" do %>
        <%= evil_icon "ei-user" %>
      <% end %>
    </div>
    <div>
      <%= link_to destroy_user_session_path,
        class: "linked-icon sign-out",
        method: :delete do %>
        <%= evil_icon "ei-external-link" %>
      <% end %>
    </div>
  </div>
</nav>