config/routes.rb
Rails.application.routes.draw do
  # namespace :settings do
  #   get 'users/show'
  #   get 'users/update'
  # end
  # get 'posts/create'
  # get 'timelines/index'
  # get 'timelines/show'
  devise_for :users
  root to: 'home#index'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  namespace :settings do
    resource :user, only: %i[show update]
  end
  authenticate :user do
    resources :timelines,
              only: %i[index show],
              param: :username
    resources :posts, only: %i[create show]
    resources :bonds, param: :username do
      member do
        post :follow
        post :unfollow
        post :accept
        post :reject
        get :followers
        get :following
      end
    end
  end
  namespace :api do
    namespace :v1 do
      resources :places, only: [:index]
    end
  end
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  def index
    @posts = Post.not_reply.where(user_id: [
                                    current_user.id,
                                    *current_user.followings.pluck(:id)
                                  ]).includes(postable: [:place]).order('created_at DESC')
  end

  def show
    @visited_user = User.find_by_username!(params[:username])
    @posts = Post.written_by(params[:username])
                 .not_reply
                 .order('created_at DESC')
  end
end

app/views/timelines/_all.html.erb
<div class="timeline">
  <% @posts.each do |post| %>
    <div class="line-group">
      <%= render "timelines/line", post: post %>
    </div>
  <% end %>
</div>

app/views/timelines/_line.html.erb
<% user = post.user %>
<% postable = post.postable %>
<% show_replies = local_assigns.fetch(:show_replies, false) %>
<% pictures = post.pictures.with_attached_file %>
<%= render "layouts/inside_modal",
  title: "Send a reply",
  modal_class: "comment_modal_#{post.id}" do %>
  <%= render "posts/form", thread: post %>
<% end %>
<div class="picture-modals">
  <!--% post.pictures.each do |picture| %-->
  <% pictures.each do |picture| %>
    <%= render "layouts/inside_modal",
      title: "",
      modal_class: "picture_modal_#{picture.id}" do %>
      <img src="<%= rails_blob_path(picture.file) %>">
    <% end %>
  <% end %>
</div>
<div class="line flex" data-post-path="<%= post_path(post) %>">
  <div class="profile-container">
    <%= image_tag user.profile_picture_url %>
  </div>
  <div class="content">
    <div class="identifier">
      <%= link_to timeline_path(user) do %>
        <span class="name"><%= user.name %></span>
        <span class="username">@<%= user.username %></span>
      <% end %>
    </div>
    <% if postable.is_a?(Status) %>
      <%= simple_format post.postable.text %>
    <% elsif postable.is_a?(Sight) %>
      <div class="flex items-center">
        <%= evil_icon "ei-location" %>
        <p>
          <%= postable.humanized_activity_type %>
          <%= postable.place.name %>
        </p>
      </div>
    <% end %>
    <div class="pictures">
      <% post.pictures.each do |picture| %>
        <a href="#">
          <div class="picture js-modal-open"
            data-modal-class="picture_modal_<%= picture.id %>">
            <img src="<%= rails_blob_path(picture.file) %>">
          </div>
        </a>
      <% end %>
    </div>
    <div class="controls">
      <%= link_to "#" do %>
        <div class="control js-modal-open"
          data-modal-class="comment_modal_<%= post.id %>">
          <%= evil_icon "ei-comment" %>
          <% if post.replies.any? %>
            <span>&nbsp;<%= post.replies.count %></span>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% if post.replies.any? %>
  <div class="replies">
    <% post.replies.each do |reply| %>
      <%= render "timelines/line", post: reply %>
    <% end %>
  </div>
<% end %>

app/views/timelines/_profile_header.html.erb
<div class="profile-header">
  <div class="card">
    <div class="picture-container">
      <%= image_tag user.profile_picture_url %>
    </div>
    <div class="content">
      <p class="username">@<%= user.username %></p>
      <p class="name"><%= user.name %></p>
    </div>
    <%= render "bonds/bonding_buttons", user: user %>
  </div>
  <div class="stats">
    <%= render "timelines/profile_stat",
      count: user.posts.count,
      counter: "posts",
      is_active: on_timeline?,
      link_to: timeline_path(user) %>
    <%= render "timelines/profile_stat",
      count: user.followers.count.to_s + "#{"*" if can? :see_follower_requests, user}",  
      counter: "followers",
      is_active: on_follower_list?,
      link_to: timeline_path(user) %>
    <%= render "timelines/profile_stat",
      count: user.followings.count,
      counter: "following",
      is_active: on_following_list?,
      link_to: timeline_path(user) %>
  </div>
</div>

app/views/timelines/_profile_stat.html.erb
<% is_active = local_assigns.fetch(:is_active, false) %>
<%= link_to link_to, class: "stat #{"active" if is_active}" do %>
  <p class="count"><%= count %></p>
  <p class="counter"><%= counter %></p>
<% end %>

app/views/timelines/index.html.erb
<%= render("posts/form")  %>
<%= render "timelines/all" %>

app/views/timelines/show.html.erb
<h1>Timelines#show</h1>
<p>Find me in app/views/timelines/show.html.erb</p>
<%= render "timelines/profile_header", user: @visited_user %>
<% if on_self? %>
  <%= render("posts/form")  %>
<% end %>
<!--%= render "timelines/all" %-->
<% if can? current_user, :see_timeline, @visited_user %>
  <%= render "timelines/all" %>
<% else %>
  <p style="text-align: center">These posts are protected</p>
<% end %>