config/routes.rb
Rails.application.routes.draw do
  # namespace :settings do
  #   get 'users/show'
  #   get 'users/update'
  # end
  # get 'posts/create'
  # get 'timelines/index'
  # get 'timelines/show'
  devise_for :users
  root to: 'home#index'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  namespace :settings do
    resource :user, only: %i[show update]
  end
  authenticate :user do
    resources :timelines,
              only: %i[index show],
              param: :username
    resources :posts, only: %i[create show]
    resources :bonds, param: :username do
      member do
        post :follow
        post :unfollow
        post :accept
        post :reject
        get :followers
        get :following
      end
    end
  end
  namespace :api do
    namespace :v1 do
      resources :places, only: [:index]
    end
  end
end

app/models/bond.rb
# == Schema Information
#
# Table name: bonds
#
#  id         :bigint           not null, primary key
#  state      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  friend_id  :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_bonds_on_user_id_and_friend_id  (user_id,friend_id) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (friend_id => users.id)
#  fk_rails_...  (user_id => users.id)
#
class Bond < ApplicationRecord
  STATES = [
    REQUESTING = 'requesting',
    FOLLOWING = 'following',
    BLOCKING = 'blocking'
  ].freeze
  enum state: {
    requesting: REQUESTING,
    following: FOLLOWING,
    blocking: BLOCKING
  }
  # validates :state, inclusion: { in: STATES }
  validates :state, presence: true
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  scope :following, -> { where(state: FOLLOWING) }
  scope :requesting, -> { where(state: REQUESTING) }
  # scope :blocking, -> { where(state: BLOCKING) }
end

app/controllers/bonds_controller.rb
class BondsController < ApplicationController
  delegate :visited_user, to: :helpers
  def follow
    return redirect_to timeline_path(visited_user) unless can? :follow, visited_user

    bond = Bond::Follower.call(
      current_user,
      visited_user
    )
    if bond.requesting?
      flash[:notice] = 'A follow request has been sent to ' +
                       "@#{visited_user.username} and is pending their approval."
    end
    redirect_to timeline_path(visited_user)
  end

  def unfollow
    return redirect_to timeline_path(visited_user) unless can? :unfollow, visited_user

    bond = Bond::Unfollower.call(
      current_user,
      visited_user
    )
    redirect_to timeline_path(visited_user)
  end

  def followers
    @bonded_users = visited_user.followers
  end

  def following
    @bonded_users = visited_user.followings
  end

  def accept
    Bond::Acceptor.call(visited_user, current_user)
    redirect_to timeline_path(current_user)
  end

  def reject
    Bond::Rejector.call(visited_user, current_user)
    redirect_to timeline_path(current_user)
  end
end

app/views/bonds/_bonding_buttons.html.erb
<div class="bonding-buttons">
  <% if can? :follow, user %>
    <%= link_to follow_bond_path(user), method: :post do %>
      <%= evil_icon "ei-plus", class: "green" %>
    <% end %>
  <% end %>
  <% if can? :unfollow, user %>
    <%= link_to unfollow_bond_path(user), method: :post do %>
      <%= evil_icon "ei-minus", class: "red" %>
    <% end %>
  <% end %>
</div>

app/views/bonds/_users_list.html.erb
<div class="users-list">
  <% users.each do |user| %>
    <div class="user">
      <%= link_to timeline_path(user), class: "profile-link" do %>
        <div class="picture-container">
          <%= image_tag user.profile_picture_url %>
        </div>
        <div class="content">
          <div class="identity">
            <p class="name"><%= user.name %></p>
            <p class="username">@<%= user.username %></p>
          </div>
        </div>
      <% end %>
      <%= yield user %>
    </div>
  <% end %>
</div>

app/views/bonds/followers.html.erb
<%= render "timelines/profile_header", user: visited_user %>
<% if can? :see_follower_requests, visited_user %>
  <%= render "bonds/users_list",
      users: visited_user.inward_bonds.requesting
        .map(&:user) do |user| %>
    <%= link_to accept_bond_path(user), method: :post do %>
      <div class="bonding-buttons">
        <%= evil_icon "ei-check", class: "green" %>
      </div>
    <% end %>
    <%= link_to reject_bond_path(user), method: :post do %>
      <div class="bonding-buttons">
        <%= evil_icon "ei-close-o", class: "red" %>
      </div>
    <% end %>
  <% end %>
<% end %>
<!--%= render "bonds/users_list", users: @bonded_users %-->

app/views/bonds/following.html.erb
<%= render "timelines/profile_header", user: visited_user %>
<%= render "bonds/users_list",
    users: @bonded_users do |each_user| %>
  <%= render "bonds/bonding_buttons", user: each_user %>
<% end %>